1 Objective
-----------

In this hands-on lab, you build a real Liberty application cluster and
manage it using the Liberty Admin Center, the web-based administrative
interface. Both application clusters and the Admin Center are new
capabilities in the IBM WebSphere Application Server V8.5.5 release.
Learn what a Liberty collective is, how clusters are defined, and how to
operate and manage clusters through both the command line and the Admin
Center and its tools.

In the lab, attendees set up a collective, create a cluster, deploy and
verify applications on the cluster, and perform basic operational tasks
on the cluster. After completing this lab, participants are fully
equipped to set up and operate their own production Liberty application
clusters and manage them through the command line or the new Admin
Center.

In this lab, you learn:

§ The concepts and operations of a Liberty collective and clustering
with the WebSphere Application Server Liberty profile

§ Hands-on experience creating, configuring and performing operations on
a collective and cluster

§ Hands-on experience with the Jython scripting support

§ Hands-on experience with the Admin Center, the new web-based
administrative interface

2 Prerequisite Knowledge
------------------------

§ Basic Linux knowledge +
  +

§ This lab uses gedit as the editor of choice in the command examples. +
 You are free to use any editor you wish (the VM image has vi and emacs
available).

 +
 When large amounts of text are displayed as part of an operation output
or screen shot, the important portions are highlighted or otherwise
indicated using red.

3 Step-by-Step Instructions
---------------------------

3.1 Introduction to Liberty
~~~~~~~~~~~~~~~~~~~~~~~~~~~

** Approximate time: 5 - 10 minutes +
  +
  +

These steps take you through the most basic operations supported by the
Liberty profile. This entails starting the default server, deploying an
application and dynamically changing the server's configuration.

The Liberty profile is designed to provide a world-class application
infrastructure platform as well as a compelling developer experience. +
  +
  +
